# Generated by Django 5.2.17 on 2026-09-16 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(default='Colombia', max_length=100, unique=True)),
                ('hora_inicio_diurno', models.TimeField(default='06:00')),
                ('hora_inicio_nocturno', models.TimeField(default='19:00')),
                ('recargo_hora_extra_diurna', models.DecimalField(decimal_places=2, default=1.25, help_text='Hora extra diurna: 25% de recargo.', max_digits=4)),
                ('recargo_hora_extra_nocturna', models.DecimalField(decimal_places=2, default=1.75, help_text='Hora extra nocturna: 75% de recargo.', max_digits=4)),
                ('recargo_nocturno', models.DecimalField(decimal_places=2, default=1.35, help_text='Trabajo ordinario nocturno: 35% de recargo.', max_digits=4)),
                ('recargo_dominical_o_festivo', models.DecimalField(decimal_places=2, default=1.9, help_text='Trabajo ordinario dominical o festivo: 90% de recargo.', max_digits=4)),
                ('recargo_nocturno_dominical_o_festivo', models.DecimalField(decimal_places=2, default=2.25, help_text='Trabajo ordinario nocturno en dominical/festivo: 125% de recargo.', max_digits=4)),
                ('recargo_hora_extra_dominical_o_festivo', models.DecimalField(decimal_places=2, default=2.15, help_text='Hora extra diurna en dominical/festivo: 115% de recargo.', max_digits=4)),
                ('recargo_hora_extra_nocturna_dominical_o_festivo', models.DecimalField(decimal_places=2, default=2.65, help_text='Hora extra nocturna en dominical/festivo: 165% de recargo.', max_digits=4)),
                ('horas_maximas_semanales', models.PositiveIntegerField(default=42)),
                ('horas_maximas_diarias_ordinarias', models.PositiveIntegerField(default=8)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regla laboral',
                'verbose_name_plural': 'Reglas laborales',
            },
        ),
        migrations.CreateModel(
            name='ParametroLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('smmlv', models.DecimalField(decimal_places=2, max_digits=12)),
                ('auxilio_transporte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('regla_laboral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_legales', to='reglas_laborales.reglalaboral')),
            ],
            options={
                'verbose_name': 'Parámetro legal',
                'verbose_name_plural': 'Parámetros legales',
                'ordering': ['-anio'],
                'constraints': [models.UniqueConstraint(fields=('regla_laboral', 'anio'), name='unique_parametro_legal_por_anio')],
            },
        ),
        migrations.CreateModel(
            name='DiaFestivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=150)),
                ('regla_laboral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_festivos', to='reglas_laborales.reglalaboral')),
            ],
            options={
                'verbose_name': 'Día festivo',
                'verbose_name_plural': 'Días festivos',
                'ordering': ['fecha'],
                'unique_together': {('regla_laboral', 'fecha')},
            },
        ),
    ]
