# Generated by Django 5.2.17 on 2026-09-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimientoDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptado', models.BooleanField(default=False)),
                ('otorgado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliticaTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=30, unique=True)),
                ('contenido', models.TextField()),
                ('vigente', models.BooleanField(default=False)),
                ('publicada_en', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
