# Generated by Django 5.2.17 on 2026-09-16 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0001_initial'),
        ('sucursales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marcaje',
            name='corregido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcajes_corregidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marcaje',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcajes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marcaje',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcajes_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marcaje',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcajes', to='sucursales.sucursal'),
        ),
        migrations.AddIndex(
            model_name='marcaje',
            index=models.Index(fields=['empleado', 'fecha'], name='registro_ma_emplead_7044ed_idx'),
        ),
        migrations.AddIndex(
            model_name='marcaje',
            index=models.Index(fields=['sucursal', 'fecha'], name='registro_ma_sucursa_225b53_idx'),
        ),
    ]
