# Generated by Django 5.2.17 on 2026-09-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_base', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('horas_extra', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('recargos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('retencion_fuente', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('novedades', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'verbose_name': 'Detalle de nómina',
                'verbose_name_plural': 'Detalles de nómina',
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('estado', models.CharField(default='borrador', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nómina',
                'verbose_name_plural': 'Nóminas',
                'ordering': ['-periodo_fin'],
            },
        ),
    ]
