# Generated by Django 5.2.17 on 2026-09-16 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolldetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_nomina', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payroll',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominas', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='payroll.payroll'),
        ),
        migrations.AddConstraint(
            model_name='payrolldetail',
            constraint=models.UniqueConstraint(fields=('payroll', 'user'), name='unique_detalle_usuario_por_nomina'),
        ),
    ]
