# Generated by Django 5.2.17 on 2026-09-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallenomina',
            name='horas_dominicales_o_festivas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='detallenomina',
            name='horas_extra_diurnas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='detallenomina',
            name='horas_extra_dominicales_o_festivas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='detallenomina',
            name='horas_extra_nocturnas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='detallenomina',
            name='horas_ordinarias_diurnas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='detallenomina',
            name='horas_ordinarias_nocturnas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='detallenomina',
            name='horas_extra',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total de horas extra del período (suma de todos los tipos anteriores)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='detallenomina',
            name='recargos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor monetario total de recargos y horas extra sobre el salario base', max_digits=14),
        ),
    ]
