# Generated by Django 5.2.17 on 2026-09-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_detallenomina_horas_dominicales_o_festivas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolldetail',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total de horas extra del período (sum de todos los tipos anteriores)', max_digits=8),
        ),
    ]
