# Generated by Django 5.2.17 on 2026-09-16 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('privacidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consentimientodatos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consentimientodatos',
            name='politica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='privacidad.politicatratamiento'),
        ),
        migrations.AddConstraint(
            model_name='consentimientodatos',
            constraint=models.UniqueConstraint(fields=('usuario', 'politica'), name='unique_consentimiento_usuario_politica'),
        ),
    ]
