# Generated by Django 5.2.17 on 2026-09-16 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('privacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dataconsent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataconsent',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='privacy.datapolicy'),
        ),
        migrations.AddConstraint(
            model_name='dataconsent',
            constraint=models.UniqueConstraint(fields=('user', 'policy'), name='unique_consentimiento_usuario_politica'),
        ),
    ]
