# Generated by Django 5.2.17 on 2026-09-17 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privacidad', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consentimientodatos',
            options={'ordering': ['-otorgado_en']},
        ),
        migrations.AlterModelOptions(
            name='politicatratamiento',
            options={'ordering': ['-publicada_en', '-id']},
        ),
    ]
