# Generated by Django 5.2.17 on 2026-09-17 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataconsent',
            options={'ordering': ['-granted_at']},
        ),
        migrations.AlterModelOptions(
            name='datapolicy',
            options={'ordering': ['-published_at', '-id']},
        ),
    ]
