# Generated by Django 5.2.17 on 2026-09-16 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomina', '0001_initial'),
        ('sucursales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detallenomina',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_nomina', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nomina',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominas', to='sucursales.sucursal'),
        ),
        migrations.AddField(
            model_name='detallenomina',
            name='nomina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='nomina.nomina'),
        ),
        migrations.AddConstraint(
            model_name='detallenomina',
            constraint=models.UniqueConstraint(fields=('nomina', 'usuario'), name='unique_detalle_usuario_por_nomina'),
        ),
    ]
