# Generated by Django 5.2.17 on 2026-09-16 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaborRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Colombia', max_length=100, unique=True)),
                ('daytime_start', models.TimeField(default='06:00')),
                ('nighttime_start', models.TimeField(default='19:00')),
                ('daytime_overtime_rate', models.DecimalField(decimal_places=2, default=1.25, help_text='Hora extra diurna: 25% de recargo.', max_digits=4)),
                ('nighttime_overtime_rate', models.DecimalField(decimal_places=2, default=1.75, help_text='Hora extra nocturna: 75% de recargo.', max_digits=4)),
                ('nighttime_rate', models.DecimalField(decimal_places=2, default=1.35, help_text='Trabajo ordinario nocturno: 35% de recargo.', max_digits=4)),
                ('sunday_holiday_rate', models.DecimalField(decimal_places=2, default=1.9, help_text='Trabajo ordinario dominical o festivo: 90% de recargo.', max_digits=4)),
                ('sunday_holiday_night_rate', models.DecimalField(decimal_places=2, default=2.25, help_text='Trabajo ordinario nocturno en dominical/festivo: 125% de recargo.', max_digits=4)),
                ('sunday_holiday_overtime_rate', models.DecimalField(decimal_places=2, default=2.15, help_text='Hora extra diurna en dominical/festivo: 115% de recargo.', max_digits=4)),
                ('nighttime_overtime_rate_dominical_o_festivo', models.DecimalField(decimal_places=2, default=2.65, help_text='Hora extra nocturna en dominical/festivo: 165% de recargo.', max_digits=4)),
                ('max_weekly_hours', models.PositiveIntegerField(default=42)),
                ('max_daily_regular_hours', models.PositiveIntegerField(default=8)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regla laboral',
                'verbose_name_plural': 'Reglas laborales',
            },
        ),
        migrations.CreateModel(
            name='LegalParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('minimum_wage', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('labor_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_legales', to='labor_rules.laborrule')),
            ],
            options={
                'verbose_name': 'Parámetro legal',
                'verbose_name_plural': 'Parámetros legales',
                'ordering': ['-year'],
                'constraints': [models.UniqueConstraint(fields=('labor_rule', 'year'), name='unique_parametro_legal_por_year')],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=150)),
                ('labor_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_festivos', to='labor_rules.laborrule')),
            ],
            options={
                'verbose_name': 'Día festivo',
                'verbose_name_plural': 'Días festivos',
                'ordering': ['date'],
                'unique_together': {('labor_rule', 'date')},
            },
        ),
    ]
